# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java###

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12'

- script: sudo npm install -g appcenter-cli
- script: appcenter login --token $(YOUR_TOKEN)


- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

 # /!\ For the purpose of the tutorial the passwords are visible, use "secret variable" instead like recommended by Microsoft:
 # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

- task: DownloadSecureFile@1
  name: mySecureFile2 # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  inputs:
    secureFile: production.keystore # The file name or GUID of the secure file
    #retryCount: 5 # Optional

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk' 
    apksign: true
    apksignerKeystoreFile: 'production.keystore'
    apksignerKeystorePassword: 'keystorepwd'
    apksignerKeystoreAlias: 'key0'
    apksignerKeyPassword: 'aliaspwd'
    apksignerArguments: --out $(Build.SourcesDirectory)/app/build/outputs/apk/release/my-crazy-app.release.apk
    zipalign: true

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)
    contents: '**/*.release.apk' 
    targetFolder: '$(build.artifactStagingDirectory)'
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/'
    artifactName: 'apks' 
    publishLocation: 'container'

- script: appcenter test run espresso --app "mokkapati.shruthi1-outlook.com/AndroidDev" --devices "mokkapati.shruthi1-outlook.com/android11" --app-path **/*.apk --test-series "master" --locale "en_US" --build-dir $(Build.ArtifactStagingDirectory)/app/build/outputs/apk/release/
